version: '3'
services:

  film_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0

  film_redis:
    image: redis:7.0.10-alpine

  auth_postgres:
    image: postgres:13

  auth_redis:
    image: redis:7.0.10-alpine

  auth_jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '6831:6831/udp'
      - '16686:16686'