version: '3'
services:

  # ------- films ------ #
  film_db:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0

  film_cache:
    image: redis:7.0.10-alpine

  # ------- auth ------ #
  auth_db:
    image: postgres:13

  auth_cache:
    image: redis:7.0.10-alpine
  # ------- admin ------ #

  admin_db:
    image: postgres:13
